[package]
name = "klabnik-future"
version = "0.1.0"
authors = ["WorstPractice"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-task = "0.3.5"
futures = "0.3.5"
